name: Deployment pipeline for backend

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # User Service
      - name: Install dependencies for User Service
        working-directory: household-server/user-service
        run: npm install
      - name: Check style for User Service
        working-directory: household-server/user-service
        run: npm run lint

      # Product Service
      - name: Install dependencies for Product Service
        working-directory: household-server/product-service
        run: npm install
      - name: Check style for Product Service
        working-directory: household-server/product-service
        run: npm run lint